server:
  port: 8080

spring:
  application:
    name : projectx

  profiles:
    active: develop

  docker:
    compose:
      enabled: false

  config:
    import: optional:file:.env.develop[.properties]

  datasource:
    url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USER_NAME}
    password: ${MAIL_PASSWORD}
    transport: api #api | smtp
    properties:
      mail:
        smtp:
          from: ${MAIL_FROM}

  devtools:
    restart:
      enabled: false




